# -*- coding: utf-8 -*-
"""exerc02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vX9bCfhvFsA9LOn4ccDS8LCovIQsg7_H
"""

from google.colab import drive
drive.mount('/content/drive')

import random

class Sala:
  def __init__(self, nome_sala, estado_sala):

    self.nome_sala = nome_sala
    self.estado_sala = estado_sala

  estados_sala = [0,1]

  def suja_sala(self):

    if(self.estado_sala == 0):
      self.estado_sala = random.choice(self.estados_sala)

class Agente:
  def __init__(self, sala, outraSala):
    self.sala = sala
    self.outraSala = outraSala

  pontuacao = 0

  def agir(self):

    if self.sala.nome_sala == 'A':
      if self.sala.estado_sala == 0 and self.outraSala.estado_sala == 1:
        self.move_direita()
      elif self.sala.estado_sala == 1:
        self.aspiraPo()
        if self.outraSala.estado_sala == 1:
          self.move_direita()

    elif self.sala.nome_sala ==  'B':
      if self.sala.estado_sala == 0 and self.outraSala.estado_sala == 1:
        self.move_esquerda()
      elif self.sala.estado_sala == 1:
        self.aspiraPo()
        if self.outraSala.estado_sala == 1:
          self.move_esquerda()

  def move_direita(self):
      self.sala.nome_sala = 'B'
      self.outraSala.nome_sala = 'A'

  def move_esquerda(self):
      self.sala.nome_sala  = 'A'
      self.outraSala.nome_sala = 'B'

  def noOp(self):
      pass

  def aspiraPo(self):

      self.sala.estado_sala = 0
      self.pontuacao = self.pontuacao + 1

def simulacao(salaInicial, salaDepois, estado_sala1, estado_sala2):

  salaAtual = Sala(salaInicial, estado_sala1)
  outraSala = Sala(salaDepois, estado_sala2)
  agente = Agente(salaAtual, outraSala)
  print("sala inicial:", salaInicial,   "   estado da sala:", estado_sala1, "   estado da outra sala: ", estado_sala2)

  for i in range(1000):
    agente.agir()
    salaAtual.suja_sala()
    outraSala.suja_sala()
  print(agente.pontuacao)
  return agente.pontuacao
print()
pontuacaoGlobal = []

pontuacaoGlobal.append(simulacao('A', 'B', 0, 0))
pontuacaoGlobal.append(simulacao('A', 'B', 0, 1))
pontuacaoGlobal.append(simulacao('A', 'B', 1, 0))
pontuacaoGlobal.append(simulacao('A', 'B', 1, 1))
pontuacaoGlobal.append(simulacao('B', 'A', 0, 0))
pontuacaoGlobal.append(simulacao('B', 'A', 0, 1))
pontuacaoGlobal.append(simulacao('B', 'A', 1, 0))
pontuacaoGlobal.append(simulacao('B', 'A', 1, 1))

mediaGlobal = (sum(pontuacaoGlobal))/len(pontuacaoGlobal)
print("media global = " ,mediaGlobal)

!jupyter nbconvert --to pdf /content/drive/MyDrive/ColabNotebooks/exerc02.ipynb